Objetivo 1[IV-22-23]
JaimeGM96/IV-JGM pull request #2
Opened 2022-09-22 11:45 UTC by JaimeGM96

Descripción de las historias de usuario y creación de los milestones e issues iniciales del proyecto.

Sobre los milestones
* [ ] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [ ] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [ ] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [ ] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [ ] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [ ] ¿Todos los milestones describen correctamente un producto, y no un
   concepto vago, una funcionalidad o una tarea?
* [ ] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [ ] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [ ]  ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [ ]  ¿El milestone 0 es mínimo *y* viable?
* [ ]  ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

Sobre las historias de usuarios
* [ ] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [ ] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
* [ ] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
* [ ] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?

2022-09-22 11:47 UTC, JaimeGM96 commented
Este pull request está en desarrollo, no está listo para revisar.

2022-09-23 18:13 UTC, JaimeGM96 commented
Listo para revisión.

2022-09-25 18:01 UTC, JJ requested changes
Por favor, pon los milestones en el PR, no sólo enlazados, para que se puedan comentar.

2022-09-25 18:01 UTC, JJ commented on docs/historias-usuario.md
> +El nutricionista cada vez que recibe a un cliente, ya sea nuevo o no, crea su nueva dieta, que le servirá hasta la siguiente revisión. Este es un proceso largo y tedioso que ocupa la mayor parte de s
Deberías ser más preciso con el contexto. También explicitar el proceso que se quiere acortar.

2022-09-25 18:01 UTC, JJ commented on docs/historias-usuario.md
> +El cliente visita al nutricionista para que le de una dieta para saber que es lo que tiene que comer para mejorar sus costumbres alimenticias. El cliente desea poder acceder a la dieta cuando quiera
Esto es un simple detalle de implementación y no tiene que ver con la lógica de negocio.

2022-09-29 17:56 UTC, JJ requested changes
Siguen sin estar los milestones en el PR, por lo que no puedo revisarlos.

Por otro lado, como he dicho esta mañana, las historias de usuario son sólo para clientes, no para usuarios. Cliente es quien se beneficia de la aplicación. Cómo genere el documento en principio debería ser transparente para el cliente. El cliente, por otro lado, justifica que esté en la nube, pero al no impliar ningún cambio o estar relacionado con la lógica de negocio, no tiene historia de usuario.

No se trata de que marquéis todo en la lista de comprobación. Poned una breve justificación de por qué es así.

2022-10-03 11:34 UTC, JaimeGM96 commented
¿En que parte del PR tengo que poner los milestones? Los tengo puestos en la descripción del mismo pero no me deja colocar todos en la sección derecha del PR, donde aparece la opción set milestone.

2022-10-03 11:37 UTC, JJ commented
> ¿En que parte del PR tengo que poner los milestones? Los tengo puestos en la descripción del mismo pero no me deja colocar todos en la sección derecha del PR, donde aparece la opción set milestone.

¿Y qué tienes que hacer para que aparezcan en la "sección derecha"?

2022-10-03 11:38 UTC, JaimeGM96 commented
Seleccionar uno de los milestones. Ahora mismo está marcado el primero.

2022-10-03 11:48 UTC, JJ commented
Tienes que describirlos en el texto, no sólo enlazarlos. Este PR de todas formas es difícil que se incluya en un milestone porque en él describes los milestones.

2022-10-03 17:33 UTC, JaimeGM96 commented
He creado un documento que está enlazado en el README donde se tiene acceso a los milestones.

2022-10-03 17:38 UTC, JJ commented on docs/milestones.md
> +En esta sección, se van a definir los diferentes milestones que tendrá este proyecto.
No sé lo que has creado, pero aquí no está la descripción de los milestones. Sigue igual que antes.

2022-10-03 17:40 UTC, JaimeGM96 commented
En este caso, ambos usuarios descritos en las historias de usuario serían los clientes, cada uno se beneficia de la aplicación de una forma diferente. El nutricionista quiere usar la aplicación para que le genere la dieta de su cliente y dicho cliente quiere poder verla desde cualquier sitio. La descripción de como se genera el documento es el contexto del proceso que quiere acortar usando la aplicación.

2022-10-03 17:41 UTC, JaimeGM96 commented on docs/milestones.md
> +En esta sección, se van a definir los diferentes milestones que tendrá este proyecto.
Pero la descripción de cada milestone está en el propio milestone, ¿también tiene que estar en un documento aparte?

2022-10-03 17:42 UTC, JJ commented on docs/milestones.md
> +En esta sección, se van a definir los diferentes milestones que tendrá este proyecto.
Es lo que te llevo diciendo desde hace 3 revisiones.

2022-10-03 17:43 UTC, JJ commented
> En este caso, ambos usuarios descritos en las historias de usuario serían los clientes, cada uno se beneficia de la aplicación de una forma diferente. El nutricionista quiere usar la aplicación para que le genere la dieta de su cliente y dicho cliente quiere poder verla desde cualquier sitio. La descripción de como se genera el documento es el contexto del proceso que quiere acortar usando la aplicación.

Sólo son clientes quienes se benefician la aplicación, ya lo dije en clase. El resto son usuarios.

2022-10-03 17:46 UTC, JaimeGM96 commented on docs/milestones.md
> +En esta sección, se van a definir los diferentes milestones que tendrá este proyecto.
Ya está listo.

2022-10-03 17:48 UTC, JJ approved these changes
Te lo voy a aceptar, pero no tienes ningún milestone intermedio donde se implemente la lógica de negocio. La arquitectura por capas requiere que esto sea un milestone específico, con sus tests y validación específica.
Por favor, hazlo antes del siguiente objetivo, preferiblemente en este PR. No hace falta que me lo pongas a revisar de nuevo.

2022-10-04 11:00 UTC, JJ commented
@mauronmp aquí esta el repo en el que tienes que trabajar. Te agradecería comprobaras que efectivamente se lleva a cabo la última sugerencia

2022-10-07 08:56 UTC, merged

2022-10-10 10:16 UTC, MauronMP commented on docs/historias-usuario.md
> +El nutricionista recibe a sus clientes cada día. Cuando empieza la cita con un cliente, toma sus medidas como el peso, mdedidas de diferentes partes del cuerpo como la cintura, etc. (si es un cliente
medidas*